#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
~/.fehbg &
~/.config/polybar/launch.sh
picom -b --config /home/xelphif/.config/picom/picom.conf &
pgrep bspswallow || bspswallow &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a qutebrowser desktop='^2'
bspc rule -a librewolf desktop='^2'
bspc rule -a discord desktop='^9'
bspc rule -a Zathura state=tiled
bspc rule -a Steam desktop='^10'
